//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using Dataspace.Common;
using Dataspace.Common.Attributes;




namespace Projections.Test.Data
{
    [DataContract(Namespace = "http://Isp.DataContracts", IsReference = false)]
    [KnownType(typeof(Attribute))]
    
    [Resource("Element")]
    [Serializable]
    public partial class Element
    {
         
    
        #region Primitive Properties
        [DataMember]
        public virtual System.Guid Id
        {
          
            get;
            set;
        }
        [DataMember]
        public virtual string Name
        {
          
            get;
            set;
        }

        #endregion

        #region Navigation Properties
    
    	[DataMember]	
        [XmlIgnore]
        public virtual ICollection<Attribute> Attribute
        {
            get
            {
                if (_attribute == null)
                {
                    var newCollection = new FixupCollection<Attribute>();             
                    _attribute = newCollection;
                }
                return _attribute;
            }
            set
            {
                if (!ReferenceEquals(_attribute, value))
                {                           
                    _attribute = value;                      
                }
            }
        }
        private ICollection<Attribute> _attribute;

        #endregion

        #region Association Fixup
    
        private void FixupAttribute(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Attribute item in e.NewItems)
                {
                    item.Element = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Attribute item in e.OldItems)
                {
                    if (ReferenceEquals(item.Element, this))
                    {
                        item.Element = null;
                    }
                }
            }
        }

        #endregion

    }
}
