//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Xml.Serialization;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;
using Dataspace.Common.Attributes;
using Dataspace.Common.Attributes.CachingPolicies;



namespace Dataspace.Over.EntityFramework.Examples
{
    [DataContract(Namespace = "http://Indusoft.EdmDataContracts", IsReference = false)]
    [Resource("BaseEntity")]
    [SimpleCaching]
    
      [Serializable]
     public partial class BaseEntity
    {
        #region Primitive Properties
        [DataMember]
        public System.Guid Id
        {
          
            get;
            set;
        }

        #endregion

    }
}
